In [1]:
import numpy as np
from shape_model.gaussian_ellipsoid import gaussian_ellipsoid_shape_model
from analytical_scattering_theories.homogeneous_sphere import mie_compute_q_and_s
from bl_dda.scatterer import Target, IncidentField, DiscreteDipoles



In [2]:
# Define the shape parameters of Gaussian Random Ellipsoid (a >= b >= c)
#### length_unit= um ###
r_v_base= 0.2 # allowed range = [0.1, 0.5], volume equivalent radius of base ellipsoid
bc_ratio= 1 # allowed range = [1.0, 7.0], b/c ratio of base ellipsoid
ab_ratio= 1 # allowed range = [1.0, 2.0], a/b ratio of base ellipsoid
beta= 0.0 # standard deviation of GE surface deformation, allowed range= [0, 0.3]

In [3]:
# generate the GRE particle volume in 3D lattice
gre_shape_model= gaussian_ellipsoid_shape_model(r_v_base, bc_ratio, ab_ratio, beta)

rng= np.random.default_rng(1234)
r_points_on_GRE_surf, xyz_meshes_GRE_surf = gre_shape_model.compute_r_points_on_GRE(rng)
lattice_domain, lattice_n, lattice_grid_points= gre_shape_model.create_cuboid_lattice_that_encloses_GRE_shape(r_points_on_GRE_surf)
dist_from_GRE= gre_shape_model.find_nearest_distance_from_the_GRE_surf(lattice_grid_points, r_points_on_GRE_surf)
lattice_grid_points_is_in_target= gre_shape_model.extract_lattice_address_in_GRE_volume(gre_shape_model.lattice_lf, gre_shape_model.distance_factor, lattice_n, dist_from_GRE)

In [4]:
# Define wavelength and refractive index

# vacuum wavelength [um]
wl_0= 0.834  

# medium refractive index
m_m=1.329 
#m_m=1.0

# particle's complex refractive index
m_p_x= 1.5+0.01j  # refractive index along x axis in particle coordinate system
m_p_y= 1.5+0.01j  # refractive index along y axis in particle coordinate system
m_p_z= 1.5+0.01j  # refractive index along z axis in particle coordinate system
m_p_xyz= np.array([m_p_x, m_p_y, m_p_z], dtype=np.complex64)

# axis-averaged particle's complex refractive index
m_p_avg= (m_p_x+m_p_y+m_p_z)/3
#m_p_xyz= np.array([m_p_avg, m_p_avg, m_p_avg], dtype=np.complex64)
m_p_avg

(1.5+0.01j)

In [5]:

target= Target(gre_shape_model.name, lattice_n, gre_shape_model.lattice_lf, lattice_grid_points, lattice_grid_points_is_in_target, m_p_xyz)
lattice_n
# np.prod(lattice_n)= 269705
lattice_n, np.prod(lattice_n)

(array([17, 17, 17], dtype=int32), np.int64(4913))

In [6]:
# Define incident fields for 10-different random particle's orientations

rng= np.random.default_rng(12345)
number_of_orientations= 10 
euler_alpha_deg= rng.uniform(0,360, number_of_orientations).reshape(number_of_orientations,1)
euler_beta_deg= rng.uniform(0,180, number_of_orientations).reshape(number_of_orientations,1)
euler_gamma_deg= rng.uniform(0,360, number_of_orientations).reshape(number_of_orientations,1)

# euler_alpha_deg= np.array([0,45+180], dtype=np.float32).reshape(number_of_orientations,1)
# euler_beta_deg= np.array([0,30], dtype=np.float32).reshape(number_of_orientations,1)
# euler_gamma_deg= np.array([0,0], dtype=np.float32).reshape(number_of_orientations,1)

euler_angles_radian= np.radians(np.hstack((euler_alpha_deg,euler_beta_deg,euler_gamma_deg)))

incident_field= IncidentField(wl_0, m_m, euler_angles_radian)

np.hstack((euler_alpha_deg,euler_beta_deg,euler_gamma_deg))

array([[ 81.84096809,  44.68422863,  29.37404504],
       [114.0330023 , 170.79860733,  57.56241639],
       [287.05156464, 120.10274156, 122.43606658],
       [243.45168147,  17.26162841, 167.46953533],
       [140.79943822,  79.53113991,  95.91157018],
       [119.81301403, 159.56638548, 293.67950523],
       [215.39115129, 125.54162998,  69.58598014],
       [ 67.22430682,  58.76511553,  46.60886742],
       [242.19217585, 132.1070694 ,  32.99931056],
       [339.0490315 ,  39.624292  , 215.48448492]])

In [7]:
discrete_dipoles= DiscreteDipoles(target, incident_field)

Number of dipoles per wavelength in the particle volume: dpl= 20.84953710436821


In [8]:
discrete_dipoles.set_interaction_matrix()

In [9]:
discrete_dipoles.solve_matrix_equation()

Starting block-BiCGStab iterative solver...
iter= 0, err= 0.0156
iter= 1, err= 0.0002
block-BiCGStab converged! (iter_fin=1, err_fin=0.0002, solver time=0.3s)


In [10]:
# Compute Mie solution for the volume-equivalent sphere

r_p= discrete_dipoles.ve_radius # volume-equivalent radius of the DDA target
Q_sca_mie, Q_abs_mie, Q_ext_mie, S_fw_PCAS_mie, S_bk_OCBS_mie = mie_compute_q_and_s(wl_0,m_m,r_p,m_p_avg,nang=3)
print(Q_sca_mie, Q_abs_mie, Q_ext_mie)
print(S_fw_PCAS_mie, S_bk_OCBS_mie)

0.09837689353262594 0.04493662949384336 0.1433135230264693
(0.073400885+0.014740863j) (0.00028208116+0.0034718874j)


In [11]:
# Compare the absorption efficiency Q_abs between DDA solutions (for each orientation) and Mie solution
# Tolerance: |Q_abs/Q_abs_mie - 1| < 0.01 for every orientation

C_abs= discrete_dipoles.compute_C_abs()
Q_abs= C_abs/(np.pi*discrete_dipoles.ve_radius**2)
print(np.abs(Q_abs/Q_abs_mie - 1))

[0.00234075 0.00082194 0.00247296 0.00015358 0.00059328 0.00013724
 0.00211581 0.00278785 0.00257769 0.00216351]


In [12]:
# Compare the absorption efficiency Q_ext between DDA solutions (for each orientation) and Mie solution
# Tolerance: |Q_ext/Q_ext_mie - 1| < 0.01 for every orientation

C_ext= discrete_dipoles.compute_C_ext()
Q_ext= C_ext/(np.pi*discrete_dipoles.ve_radius**2)
print(np.abs(Q_ext/Q_ext_mie - 1))

[0.0016806  0.00110054 0.00178967 0.00048768 0.00071919 0.00056919
 0.00161458 0.00207042 0.00190878 0.00114165]


In [13]:
# Compare the polarized forward complex scattering amplitude between DDA solutions (for each orientation) and Mie solution
# Tolerance for theta-polarization (s-pol in PCAS): |S_fw_theta_dda.real/S_fw_mie.real - 1| < 0.01 and  |S_fw_theta_dda.imag/S_fw_mie.imag - 1| < 0.01 for every orientation
# Tolerance for phi-polarization (p-pol in PCAS): |S_fw_phi_dda.real/S_fw_mie.real - 1| < 0.01 and  |S_fw_phi_dda.imag/S_fw_mie.imag - 1| < 0.01 for every orientation

S_fw_PCAS_theta_P, S_fw_PCAS_phi_P= discrete_dipoles.compute_PCAS_observable_S_fw()
print(np.abs(S_fw_PCAS_theta_P.real/S_fw_PCAS_mie.real - 1), np.abs(S_fw_PCAS_theta_P.imag/S_fw_PCAS_mie.imag - 1))
print(np.abs(S_fw_PCAS_phi_P.real/S_fw_PCAS_mie.real - 1), np.abs(S_fw_PCAS_phi_P.imag/S_fw_PCAS_mie.imag - 1))

[0.00047764 0.00045355 0.00105047 0.00019587 0.00025289 0.00029319
 0.00086922 0.00145139 0.00132558 0.00145763] [1.13091108e-03 1.49521975e-03 3.50538474e-03 1.15621966e-03
 9.42849587e-04 1.52725444e-03 5.19896757e-03 1.35384086e-03
 4.15879410e-03 9.42993530e-05]
[1.68136706e-03 3.92494120e-04 1.23568338e-03 1.73263908e-05
 3.88668884e-04 3.83416739e-04 1.06637646e-03 1.13172555e-03
 1.05721913e-03 5.63013676e-04] [2.23022787e-03 7.05919518e-04 7.38931623e-05 2.13163522e-03
 4.95584409e-04 3.88805721e-04 1.96986239e-03 2.78694159e-03
 3.41286834e-04 2.18894450e-03]


In [14]:
S_bk_OCBS_P= discrete_dipoles.compute_OCBS_observable_S_bk()

In [15]:
S_bk_OCBS_P, S_bk_OCBS_mie


(array([ 0.00135109+0.00372118j, -0.00141074+0.0032077j ,
         0.00144375+0.00374011j, -0.00083594+0.00331428j,
        -0.00124069+0.00324015j, -0.00053676+0.00336732j,
         0.00109785+0.00367712j,  0.00171865+0.00379029j,
         0.00151792+0.00375321j,  0.00119338+0.00369024j]),
 np.complex64(0.00028208116+0.0034718874j))