In [1]:
import numpy as np
from mvp_fft.mvp_fft import MBT_fft_init, MBT_fft_mvp

In [2]:
n= np.array([2,2,2],dtype=int)
f=3
lf=1
k=1

## MBT projection of the non-diagonal block of DDA matrix
Au_til= MBT_fft_init(n,f,lf,k)

Au_til


array([-2.94595619e+01-5.01440750e+01j, -8.74083416e+00-5.55374583e+00j,
       -1.66162104e+01-6.07428992e+00j, -4.20253599e+00-6.56409232e+00j,
        1.18681823e+01+2.35748483e+00j, -5.55299774e+00-2.63867583e+00j,
       -1.34850957e+01-5.22747768e+00j,  3.24493622e+00-3.92509520e-02j,
       -6.18772841e+00-4.22750640e+00j,  9.20952718e+00-9.92432943e+00j,
        1.05042507e+01+7.04687898e+00j, -1.10178390e+00-5.46763241e+00j,
        5.71987130e+00+1.48089264e+01j, -4.77652089e+00-3.22415197e+00j,
        4.58349766e+00+3.36442611e+00j, -3.98734444e+00-1.62050432e+01j,
        1.68694048e+00+7.10247393e+00j, -3.67667141e-01-3.40274022e+00j,
       -1.39807220e+01+1.53226127e+01j, -4.28532472e+00-3.73797977e-01j,
       -8.52359059e+00-7.40450838e+00j,  9.85944912e-01-1.08269003e+00j,
        8.68875172e+00-2.16936259e+00j, -7.71650686e+00+1.26570332e+00j,
        5.48945545e+00+8.63754046e+00j, -3.34377231e+00+1.06090009e+01j,
        2.73961327e+00-2.13640217e+01j,  4.73019998

In [3]:
p_hat= np.arange(1, f*np.prod(n)+1, dtype=complex)
p_hat

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
        8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j, 14.+0.j,
       15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j, 20.+0.j, 21.+0.j,
       22.+0.j, 23.+0.j, 24.+0.j])

In [4]:
q_hat= MBT_fft_mvp(n, f, Au_til, p_hat)

q_hat

array([ -69.58824918-79.10245816j,  -93.51322552-86.24641607j,
       -139.43509898-96.59048401j,   57.84135128-32.00371066j,
        -69.08032786-68.87622105j, -100.92915222-74.99929132j,
        -62.33067889-62.21716062j,   51.16319418-37.38305853j,
       -111.06795504-73.37368996j,    6.7069353 -43.63884502j,
         19.73922865-46.49308171j,  -60.23757093-50.38968476j,
        -85.92991895-60.21820016j, -102.81837074-65.25165924j,
         43.05659362-42.94566412j,  -23.53557365-44.14436912j,
        -57.84474416-45.56011003j,   17.48938563-48.7632313j ,
        -54.02347395-40.54727759j,  -27.28535199-47.877489j  ,
          0.70731394-49.64211449j,  -99.31886433-58.56512851j,
        -79.25004643-59.30886636j,  -37.18433141-56.85249419j])