In [1]:
import pyfftw
import numpy as np


In [2]:
a = pyfftw.empty_aligned(128, dtype='complex64')
b = pyfftw.empty_aligned(128, dtype='complex64')

fft_object = pyfftw.FFTW(a, b, direction='FFTW_FORWARD')

In [3]:
c = pyfftw.empty_aligned(128, dtype='complex64')
ifft_object = pyfftw.FFTW(b, c, direction='FFTW_BACKWARD')

In [4]:
# Generate some data
ar, ai = np.random.randn(2, 128)
a[:] = ar + 1j*ai

In [5]:
fft_object.execute()

In [6]:
#a1 = pyfftw.empty_aligned(128, dtype='complex64')
a1= np.zeros(128, dtype=np.complex64)
b1= np.zeros(128, dtype=np.complex64)
ar, ai = np.random.randn(2, 128)
a1[:] = ar + 1j*ai
a1[:]

array([ 0.8389406 -1.07718611e+00j,  2.0663497 +1.96602857e+00j,
       -1.5159248 -3.52828532e-01j, -1.5178211 -8.83814096e-01j,
       -0.5722359 -4.56406325e-01j,  0.9377988 +1.33532274e+00j,
       -1.4557295 -1.80877113e+00j, -1.674316  -4.44320172e-01j,
       -0.755667  +8.02814543e-01j, -0.08287707-1.05497563e+00j,
       -1.2997154 -3.13578188e-01j, -1.0146385 -2.98017234e-01j,
        0.16980243-7.36607671e-01j,  1.2090472 -1.68716788e-01j,
       -0.039107  +1.61303258e+00j,  1.573841  -6.43763423e-01j,
        0.53866273-3.38498093e-02j,  1.1977895 -3.01984280e-01j,
       -1.1537042 +1.08847809e+00j,  0.39322433-1.80493653e+00j,
        1.6113356 +1.25529420e+00j, -0.6915954 -2.04087704e-01j,
       -1.199082  -1.84932530e+00j,  0.11127754-2.71267384e-01j,
        2.251174  +1.16077387e+00j, -0.18684374-7.01676071e-01j,
        0.212527  -1.05559957e+00j, -0.27207977+1.67582408e-01j,
        0.87158614+1.76426136e+00j,  0.6918651 -8.44842419e-02j,
        1.0884457 +2.9357

In [7]:

fft_object.update_arrays(a1, b1)
b1

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
      

In [8]:
fft_object.execute()

In [9]:
b1

array([  2.2322438 -13.8614235j , -14.865723   -9.517603j  ,
       -10.528866  +12.010515j  , -15.481464   +1.013485j  ,
        -7.606286   -3.8872707j ,   1.4450955 +21.828592j  ,
       -20.257048   +4.4348717j ,   5.1839523  -9.73139j   ,
         0.22613144 +3.5901752j ,  11.9515505  -6.334933j  ,
        13.045051   +9.470527j  ,   3.7733016 -19.82879j   ,
         3.6933308  -9.554811j  , -16.243605  +17.204128j  ,
         3.0178843  +1.0679867j , -13.181839   -9.509331j  ,
        -3.599969  -16.012047j  ,   6.4611177  -0.2267828j ,
        21.766132   -3.309658j  ,  -2.9701931  -7.254754j  ,
         9.235779   -1.3374324j ,  11.9735985  -1.7056527j ,
        17.093792   -6.2563543j ,   7.7255387  -7.839385j  ,
         2.1053805  +8.2209015j ,   2.0525608  +7.9357295j ,
         9.642807   -3.586001j  ,   3.3273506  +0.2698412j ,
        15.388287   -5.7547708j ,  17.641605  -13.196658j  ,
         3.4908357 +20.018135j  ,   9.05435    -3.7337358j ,
        14.532162   -2.4

In [10]:
c1= np.zeros(128, dtype=np.complex64)
ifft_object.update_arrays(b1, c1)

In [12]:
ifft_object.execute()
c1/128

array([ 0.83894056-1.0771861e+00j,  2.0663497 +1.9660286e+00j,
       -1.5159247 -3.5282868e-01j, -1.517821  -8.8381398e-01j,
       -0.57223576-4.5640641e-01j,  0.9377986 +1.3353226e+00j,
       -1.4557296 -1.8087710e+00j, -1.6743159 -4.4432020e-01j,
       -0.75566685+8.0281436e-01j, -0.08287692-1.0549757e+00j,
       -1.2997155 -3.1357807e-01j, -1.0146385 -2.9801726e-01j,
        0.16980234-7.3660737e-01j,  1.2090472 -1.6871658e-01j,
       -0.03910689+1.6130325e+00j,  1.5738407 -6.4376336e-01j,
        0.53866273-3.3849776e-02j,  1.1977895 -3.0198425e-01j,
       -1.1537044 +1.0884778e+00j,  0.3932243 -1.8049365e+00j,
        1.6113355 +1.2552941e+00j, -0.6915954 -2.0408773e-01j,
       -1.1990818 -1.8493253e+00j,  0.11127746-2.7126729e-01j,
        2.251174  +1.1607738e+00j, -0.18684357-7.0167601e-01j,
        0.21252683-1.0555999e+00j, -0.27207977+1.6758227e-01j,
        0.871586  +1.7642611e+00j,  0.691865  -8.4484279e-02j,
        1.0884454 +2.9357120e-01j,  0.6987267 +1.984247