In [81]:
import h5py
import numpy as np

In [82]:
# ── sweep parameters ──────────────────────────────────────────────────────────
# (wl_0, m_m) pairs: each row is [vacuum wavelength [um], medium refractive index]
wl_m_m_pairs = [
    [0.633,  1.330],   # 633 nm (赤), 水
    [0.8337, 1.329]   # 834 nm (近赤外), 水
]

# Particle refractive index sweep: each row is [m_p_x, m_p_y, m_p_z] (complex)
# Isotropic example:  [[1.5+0.01j, 1.5+0.01j, 1.5+0.01j]]
# Anisotropic example: rows with different x/y/z components
m_p_xyz_list = [
    [1.5+0j,    1.5+0j,    1.5+0j   ],   # 等方性・無吸収
    [1.55+0j,    1.55+0j,    1.55+0j   ],   # 等方性・無吸収
]

# Shape parameter sweep lists
r_v_base_list = [0.1, 0.2, 0.3, 0.4]   # [um] volume-equivalent radius of base ellipsoid
bc_ratio_list  = [3]          # b/c semi-axis ratio
ab_ratio_list  = [1]          # a/b semi-axis ratio
gre_beta_list  = [0]          # GRE surface roughness std-dev

num_orientations = 100         # number of random particle orientations per particle

filename = "pcas_ocbs_simulated_data.hdf5"

# ── dimension sizes ────────────────────────────────────────────────────────────
N_pairs = len(wl_m_m_pairs)
N_m_p   = len(m_p_xyz_list)
N_rv    = len(r_v_base_list)
N_bc    = len(bc_ratio_list)
N_ab    = len(ab_ratio_list)
N_bt    = len(gre_beta_list)

# Dataset shape shorthands
shape_geo  = (         N_rv, N_bc, N_ab, N_bt)                     # geometry only (r_ve)
shape_cond = (N_pairs, N_m_p, N_rv, N_bc, N_ab, N_bt)              # scalar per condition
shape_ori  = (N_pairs, N_m_p, N_rv, N_bc, N_ab, N_bt, num_orientations)      # per orientation
shape_ang  = (N_pairs, N_m_p, N_rv, N_bc, N_ab, N_bt, num_orientations, 3)   # euler angles

# ── create HDF5 file ──────────────────────────────────────────────────────────
with h5py.File(filename, "w") as f:
    grp = f.create_group("target")
    grp.attrs['light_source']       = 'Thorlabs SLD830S-A10 @ I=140mA, T=25C'
    grp.attrs['polarization_state'] = ('left-handed circular: '
                                       'E0_theta=1/sqrt(2), E0_phi=1j/sqrt(2)')
    grp.attrs['num_orientations']   = num_orientations

    # wl_m_m_pairs: (N_pairs, 2), columns = [wl_0_um, m_m]
    grp.create_dataset("wl_m_m_pairs",  data=wl_m_m_pairs,  dtype=np.float64)
    # m_p_xyz_list: (N_m_p, 3), columns = [m_p_x, m_p_y, m_p_z]
    grp.create_dataset("m_p_xyz_list",  data=m_p_xyz_list,  dtype=np.complex128)
    grp.create_dataset("r_v_base_list", data=r_v_base_list, dtype=np.float64)
    grp.create_dataset("bc_ratio_list", data=bc_ratio_list, dtype=np.float64)
    grp.create_dataset("ab_ratio_list", data=ab_ratio_list, dtype=np.float64)
    grp.create_dataset("gre_beta_list", data=gre_beta_list, dtype=np.float64)

    sd = grp.create_group("simulated_data")
    sd.attrs['scattering_code'] = 'block-DDA_Py (discrete dipole approximation)'
    sd.attrs['orientation']     = ('random ZYZ Euler angles: '
                                   'alpha in [0,2pi), beta in [0,pi), gamma in [0,2pi)')
    sd.attrs['units']           = 'r_ve:[um], euler_angles:[rad], C:[um^2], S:[um]'
    sd.attrs['S_definition']    = ('S(0)_theta = S11(0)+1j*S12(0), '
                                   'S(0)_phi = S22(0)-1j*S21(0), '
                                   'S(180) = (S11+S22+1j*S12-1j*S21)(180)/sqrt(2), '
                                   'per Mishchenko 2000')

    def ds(name, shape, dtype, definition):
        """Create a dataset with a definition attribute."""
        d = sd.create_dataset(name, shape, dtype=dtype)
        d.attrs['definition'] = definition
        return d

    ds("r_ve",            shape_geo,  np.float64,
       "volume-equivalent radius [um] from discretised particle volume")
    ds("Euler_angles",    shape_ang,  np.float64,
       "ZYZ Euler angles (alpha,beta,gamma) rotating particle frame from lab frame [rad]")
    ds("C_abs",           shape_ori,  np.float64,    "absorption cross section per orientation [um^2]")
    ds("C_ext",           shape_ori,  np.float64,    "extinction cross section per orientation [um^2]")
    ds("S_fw_PCAS_theta", shape_ori,  np.complex128, "forward-scattering amplitude S(0)_theta per orientation [um]")
    ds("S_fw_PCAS_phi",   shape_ori,  np.complex128, "forward-scattering amplitude S(0)_phi per orientation [um]")
    ds("S_bk_OCBS",       shape_ori,  np.complex128, "backward-scattering amplitude S(180) per orientation [um]")
    ds("C_abs_mie",       shape_cond, np.float64,    "Mie C_abs of volume-equivalent sphere [um^2]")
    ds("C_ext_mie",       shape_cond, np.float64,    "Mie C_ext of volume-equivalent sphere [um^2]")
    ds("S_fw_PCAS_mie",   shape_cond, np.complex128, "Mie S(0) of volume-equivalent sphere [um]")
    ds("S_bk_OCBS_mie",   shape_cond, np.complex128, "Mie S(180) of volume-equivalent sphere [um]")

print(f"Created {filename}")
print(f"  wl_m_m_pairs : {wl_m_m_pairs}")
print(f"  m_p_xyz_list : {m_p_xyz_list}")
print(f"  shape dims   : N_pairs={N_pairs}, N_m_p={N_m_p}, N_rv={N_rv}, N_bc={N_bc}, N_ab={N_ab}, N_bt={N_bt}")
print(f"  shape_cond   : {shape_cond}")
print(f"  shape_ori    : {shape_ori}")

Created pcas_ocbs_simulated_data.hdf5
  wl_m_m_pairs : [[0.633, 1.33], [0.8337, 1.329]]
  m_p_xyz_list : [[(1.5+0j), (1.5+0j), (1.5+0j)], [(1.55+0j), (1.55+0j), (1.55+0j)]]
  shape dims   : N_pairs=2, N_m_p=2, N_rv=4, N_bc=1, N_ab=1, N_bt=1
  shape_cond   : (2, 2, 4, 1, 1, 1)
  shape_ori    : (2, 2, 4, 1, 1, 1, 100)


In [83]:
f= h5py.File(filename, "a")

In [84]:
f['target'].keys()

<KeysViewHDF5 ['ab_ratio_list', 'bc_ratio_list', 'gre_beta_list', 'm_p_xyz_list', 'r_v_base_list', 'simulated_data', 'wl_m_m_pairs']>

In [85]:
f['target']['simulated_data']['r_ve'][0]

array([[[0.]]])

In [86]:
f['target']['m_p_xyz_list'][:]

array([[1.5 +0.j, 1.5 +0.j, 1.5 +0.j],
       [1.55+0.j, 1.55+0.j, 1.55+0.j]])

In [87]:
f['target']['wl_m_m_pairs'][:]   # (N_pairs, 2): columns = [wl_0_um, m_m]

array([[0.633 , 1.33  ],
       [0.8337, 1.329 ]])

In [88]:
f.close()